---
title: "analysis"
subtitle: Due 12/18/2023
author: "Evan Kim"
format: 
  html:
    self-contained: true
---

```{r setup, echo=FALSE, message=FALSE}
#| include: false
library(tidyverse)
library(sf)
library(dplyr)
library(knitr)

# If running on the department server, uncomment the lines below
#
# - We would also recommend rendering this assignment on https://hypatia.stat.duke.edu 
#   or https://katherinej.stat.duke.edu for better performance.

#flexiblas::flexiblas_load_backend("OPENBLAS-THREADS") |>
# flexiblas::flexiblas_switch()
# flexiblas::flexiblas_set_num_threads(8)
```

-----



```{r}
# Read the CSV file into a dataframe
df <- read.csv('data/SPY_data_wrangling/SPY_ready_for_analysis.csv', header = TRUE)

# Binomial model
model <- glm(MondayOpenComparedToFridayCloseChangeInPercent ~ FridayCloseComparedToThursdayCloseChangeInPercent + FridayIntradayChangeInPercent, 
                      data = df, family = gaussian)

# Print the summary of the model
summary(model)


```

```{r}
df2 <- read.csv('data/SPY_data_wrangling/SPY_ready_for_analysis.csv', header = TRUE)

# Binomial model
model2 <- glm(WasMondayOpenHigherThanFridayClose	 ~ didFridayCloseHigherThanThursdayClose, 
                      data = df, family = binomial)

# Print the summary of the model
summary(model2)
```


